version: "3.9"

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3307:3306

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
      - NODE_VERSION_DEVELOP=20.19.2  # 👈 Ensure this is declared
    working_dir: /home/frappe
    volumes:
      - .:/workspace                  # 👈 Mount local repo
      - ./hrms:/workspace/hrms       # 👈 Explicitly mount your local HRMS app folder
    ports:
      - 8000:8000                    # 👈 Frappe web port
      - 9000:9000                    # 👈 SocketIO (can be changed if in use)

volumes:
  mariadb-data:
